#!/bin/bash

. $(find . -name crema-common-lib.sh)

# Adb ------------------------------------------------------
show_info "Start adb"
adb kill-server
adb start-server
echo
show_info "ADB information:"
show_info "Device:"
adb devices -l

show_info "Display:"
adb shell wm size
adb shell wm density
echo
show_info "Packages:"
adb shell pm list packages -f
echo
show_info "Features:"
adb shell cmd package list features
echo
show_info "Props:"
adb shell getprop
echo
show_info "Dumpsys (remove -l for more info):"
adb shell dumpsys -l
echo
show_info "Sensors:"
adb shell dumpsys sensorservice
echo
show_info "Input:"
adb shell dumpsys input
echo
show_info "Battery:"
adb shell dumpsys batteryproperties
echo
show_info "Services:"
adb shell service list
echo
show_info "Disk:"
adb shell df -h
echo
show_info "Mounts:"
adb shell mount
echo
show_info "CPU/Memory:"
adb shell cat /proc/cpuinfo
echo
show_info "Memory:"
adb shell cat /proc/meminfo
echo
show_info "Settings:"
adb shell settings list system
adb shell settings list global
adb shell settings list secure
show_ok "ADB commands done"
echo

# Fastboot ------------------------------------------------------
show_info "Reboot to fastboot"
adb reboot fastboot
sleep 15
show_info "Fastboot information:"
show_info "Device:"
fastboot devices
echo
show_info "Flashing:"
fastboot flashing get_unlock_ability
echo
show_info "Vars:"
fastboot getvar all
echo
show_info "OEM information:"
fastboot oem device-info
echo
fastboot reboot
show_ok "Done"
ding
